name: build-ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry==1.1.4
    - name: build & install
      run: |
          poetry install
    - name: pytest
      run: |
          poetry run pytest --cov git_repo_move -s -v test
    - name: black
      run: |
          poetry run black --check .
